/* ════════════════════════════════════════════════════════════════
   TWO-HEADED COMMANDER — banned-cards.js
   ════════════════════════════════════════════════════════════════

   HOW TO ADD A CARD
   ─────────────────
   Copy any existing entry and change the fields:

     { name, type, cat, pill, origin, reason }

   VALID VALUES FOR cat (used by the filter buttons):
     "banned-commander" → Banned as Commander Only filter
     "extra-turn"       → Extra Turns filter
     "tutor"            → Tutors filter
     "fast-mana"        → Fast Mana filter
     "big-life"         → Big Life Total filter
     "life-manip"       → Life Manipulation filter
     "combo"            → Combo filter
     "hard-stax"        → Hard Stax filter
     "misc"             → Misc filter
     "commander"        → Commander Ban filter (official RC banned list)

   VALID VALUES FOR pill (the coloured tag in the card header):
     "pill-edh"    → purple  — banned in EDH
     "pill-2hg"    → gold    — banned in Two-Headed Giant
     "pill-both"   → red     — banned in both EDH and 2HG
     "pill-2hc"    → blue    — unique ban for this format

   ════════════════════════════════════════════════════════════════ */

const BANNED_CARDS = [

  // ── BANNED AS COMMANDER ONLY ──────────────────────────────────

  { name: "Braids, Cabal Minion", type: "Legendary Creature — Human Minion", cat: "banned-commander", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Each player sacrifices a permanent at the beginning of their upkeep. Braids decks are usually built to play it early and have a lot of expendable permanents. While this commander can adversely affect a player's teammate, the forced resource denial from an uncontested early Braids can often lead to non-games." },
  { name: "Krark, the Thumbless", type: "Legendary Creature — Goblin Shaman", cat: "banned-commander", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Flip a coin on each instant or sorcery — win to copy it; lose to return to hand. This commander usually helms storm decks, aiming at chaining a lot of spells early. The fact that it has the partner ability enables the use of two additional colors. The constant coin flip mechanic often leads to exceedingly long turns." },
  { name: "Magda, Brazen Outlaw", type: "Legendary Creature — Dwarf Berserker", cat: "banned-commander", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Tapped dwarves create Treasure tokens; five Treasures deploy any artifact or Dragon for free. Treasures are now very easy to produce and the deck can tutor overwhelming board states too quickly, with minimal mana investment." },
  { name: "Sisay, Weatherlight Captain", type: "Legendary Creature — Human Soldier", cat: "banned-commander", pill: "pill-edh", origin: "Banned — tutor", reason: "Taps for mana equal to her power to tutor a legendary permanent of that CMC or less directly into play. With any power boost, chains legendary permanents onto the battlefield for free. Once on the battlefield it leads to repetitive game play and can take many different lines to counter interaction." },
  { name: "Zur the Enchanter", type: "Legendary Creature — Human Wizard", cat: "banned-commander", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Whenever Zur attacks, tutor any enchantment with CMC 3 or less directly into play. There is a large number of oppressive enchantments in this color combination, and Zur can put them on the battlefield too consistently, leading to repetitive game play." },
  { name: "Etali, Primal Conqueror", type: "Legendary Creature — Elder Dinosaur", cat: "banned-commander", pill: "pill-2hc", origin: "Banned — free spell cheat", reason: "When it enters, cast the top card of each opponent's library for free. Even with the 2HC ban list, Etali is in the most explosive color combination and can be cast as early as turn 1, and often on turn 3. Its trigger helps accumulating resources too quickly, and often generates more copies of Etali, leading to an unsurmountable board state." },
  { name: "Kinnan, Bonder Prodigy", type: "Legendary Creature — Human Druid", cat: "banned-commander", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "All nonland mana sources produce one additional mana. Costing only 2 mana, Kinnan is both an enabler and a win condition on its own, and has combo potential with a large number of cards in the format. Given other bannings he is fine in the deck, but is deemed too oppressive as a commander." },

   
  // ── EXTRA TURNS ────────────────────────────────────────────────

  { name: "Alchemist's Gambit", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "A foretell extra-turn spell castable with any color of mana. The foretell mechanic dodges certain interaction. As with all extra turn spells, in 2HC this means both teammates untap and act simultaneously — equivalent to two extra turns in any solo format." },
  { name: "Alrund's Epiphany", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Grants an extra turn plus two 1/1 flying tokens, and can be foretold to dodge interaction. In 2HC, the combined team extra turn is already game-winning on its own; the token bonus makes it even more one-sided." },
  { name: "Beacon of Tomorrows", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Grants an extra turn and shuffles back into the library — impossible to mill away, enabling an infinite loop with any tutor. In 2HC, infinite team extra turns mean opponents never take another turn." },
  { name: "Lost Isle Calling", type: "Instant", cat: "extra-turn", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "An effect that scales with the number of players involved, creating disproportionate value in a four-player team setting. The cooperative structure allows both players to benefit from a single casting in ways that far exceed its power level in any solo format." },
  { name: "Capture of Jingzhou", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "A clean five-mana extra turn with no drawback. In 2HC, an extra turn means both teammates untap, draw, and act simultaneously — roughly equivalent to two extra turns in any solo format." },
  { name: "Chance for Glory", type: "Instant", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Three mana for an extra turn plus indestructible on all creatures. The lose-at-end-of-turn clause is negated identically to Final Fortune with Sundial of the Infinite or Angel's Grace." },
  { name: "Emrakul, the Aeons Torn", type: "Legendary Creature — Eldrazi", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Cannot be countered, gives an extra turn after casting, has protection from colored spells, trample, and annihilator 6. In 2HC the extra turn means both teammates attack with an unkillable 15/15 while opponents have already sacrificed 6 permanents each — an immediate and unrecoverable game state." },
  { name: "Final Fortune", type: "Instant", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "One mana for an extra turn. The delayed lose trigger is trivially negated by Sundial of the Infinite, Angel's Grace, or a teammate holding the safety valve — making this a one-mana extra turn with zero downside in a team context." },
  { name: "Glorious End", type: "Instant", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Ends the current turn at instant speed and grants an extra turn. Can deny an opponent's entire turn when cast during their upkeep, then chain into a full team extra turn. The delayed lose trigger is easily negated." },
  { name: "Gonti's Aether Heart", type: "Legendary Artifact", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Accumulates aether counters from entering artifacts and can exile itself to grant an extra turn. In artifact-heavy Commander decks, charging this is passive and automatic. Sacrificing it mid-game for a free extra turn requires no additional mana." },
  { name: "Ichormoon Gauntlet", type: "Artifact", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Proliferates planeswalkers enabling ultimates many turns early, and has a zero-mana ability that grants an extra turn once per turn. In 2HC, rapidly charging a Ral Zarek or Mu Yanling is a near-certain win line with a teammate providing board protection." },
  { name: "Karn's Temporal Sundering", type: "Legendary Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Grants an extra turn while bouncing a nonland permanent. The legendary requirement is trivial in Commander. In 2HC, bouncing a key blocker while both teammates gain an additional simultaneous turn is a game-ending play." },
  { name: "Last Chance", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Identical to Final Fortune in effect — one mana for an extra turn with a deferred lose trigger. Easily negated by the same combo pieces. Another enabler of one-mana extra turns with zero downside when a teammate holds a safety valve." },
  { name: "Lighthouse Chronologist", type: "Creature — Human Wizard", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "At level 7, opponents skip their extra turns and you gain an extra turn each upkeep. Once leveled, this creates a permanent soft lock — the team takes infinite turns every upkeep while opponents are denied all extra turns indefinitely." },
  { name: "Magistrate's Scepter", type: "Artifact", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Accumulate three charge counters to take an extra turn. With proliferate effects ubiquitous in Commander, charges instantly. Creates a repeatable extra turn engine that fires every two turns with any meaningful proliferate support." },
  { name: "Magosi, the Waterveil", type: "Land", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Can skip a turn to place an eon counter, then return itself to hand to cash in the counter for an extra turn. This loop generates infinite extra turns over time with no mana cost beyond the initial investment." },
  { name: "Medomai the Ageless", type: "Legendary Creature — Sphinx", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Grants an extra turn whenever it deals combat damage to a player. In 2HC, a teammate clears blockers for Medomai to connect, then both players take a full extra simultaneous turn — repeatable every attack." },
  { name: "Mu Yanling", type: "Legendary Planeswalker", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Ultimate grants an extra turn while creating a 4/4 flying token. In 2HC, a teammate protects Mu Yanling while she charges toward a game-winning extra turn with a large evasive body included." },
  { name: "Nexus of Fate", type: "Instant", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Extra turn at instant speed that shuffles back into the library — immune to graveyard hate. A single copy with sufficient mana creates infinite extra turns for the casting team with both players acting every cycle while opponents never take another turn." },
  { name: "Notorious Throng", type: "Tribal Sorcery — Rogue", cat: "extra-turn", pill: "pill-2hg", origin: "Banned — extra turns (see manifesto)", reason: "Prowl cost grants an extra turn when cast after a rogue dealt combat damage. Rogue tribal makes prowl trivially achievable. In 2HC, a single unblocked rogue enables a free extra team turn with both players untapping simultaneously." },
  { name: "Part the Waterveil", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Six mana for an extra turn; can be awoken to also create a 6/6 token. Efficient enough to splash into tempo strategies, and the body makes it a win condition even before the extra turn resolves." },
  { name: "Plea for Power", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Council's dilemma where opponents choose extra turn or draw three. In 2HC the casting team always votes extra turn — and at minimum one opponent will also vote extra turn, guaranteeing the team gets one regardless of how opponents split their votes." },
  { name: "Ral Zarek", type: "Legendary Planeswalker", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Ultimate flips five coins, giving an extra turn per heads. With a proliferate teammate, Ral can ultimate quickly. The expected 2.5 extra turns per ultimate in 2HC translates to five combined team turns — almost always an immediate win." },
  { name: "Sage of Hours", type: "Creature — Human Wizard", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Remove five +1/+1 counters to take an extra turn. Explosive with proliferate and counter-doubling effects. In 2HC, a teammate running a +1/+1 counter strategy passively charges Sage of Hours — creating easy access to infinite extra turns." },
  { name: "Regenerations Restored", type: "Sorcery", cat: "extra-turn", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "A join forces sorcery where each player contributes mana to put lands from hand into play. In 2HC, both teammates contributing mana accelerates both mana bases simultaneously in a single spell — creating a land advantage that compounds over subsequent turns." },
  { name: "Rise of the Eldrazi", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — free cheat", reason: "Ten mana to put any Eldrazi from hand or library directly into play. In 2HC, combined mana production from both teammates makes ten mana reachable far earlier than in solo Commander — instantly deploying any Eldrazi titan." },
  { name: "Savor the Moment", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Three mana for an extra turn without untapping. The no-untap clause is largely irrelevant since both players can still attack, play lands, and build board state. A teammate being fully untapped makes the restriction trivial." },
  { name: "Seedtime", type: "Instant", cat: "extra-turn", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "If an opponent cast a blue spell this turn, take an extra turn. In 2HC, opponents running blue are nearly universal in Commander — any blue spell cast during the opposing team's simultaneous turn triggers this, providing near-guaranteed access to a cheap extra turn every round." },
  { name: "Teferi, Master of Time", type: "Legendary Planeswalker", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Activates twice per turn cycle — on each player's turn. In 2HC with four players, Teferi activates up to four times per round. His ultimate exiles a target player until they win a coin flip — in 2HC, permanently exiling one opposing player eliminates their entire team." },
  { name: "Teferi, Timebender", type: "Legendary Planeswalker", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Ultimate takes an extra turn with seven loyalty. With a teammate defending him, reaching the ultimate is reliably fast. The extra turn is game-ending in team formats, and Teferi's bounce and draw abilities maintain board parity during charging." },
  { name: "Temporal Extortion", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Opponents may each pay half their life to counter it. In 2HC, the opposing team shares 60 life — paying half means losing 30 life to stop a single extra turn. The tax is nearly unaffordable, forcing the extra turn through in virtually every game state." },
  { name: "Temporal Manipulation", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Five mana, no conditions, no drawback. In 2HC, both players untapping and acting again simultaneously is equivalent to two extra turns in any solo format." },
  { name: "Temporal Mastery", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Two mana with miracle — an absurdly cheap extra turn enabled by any topdeck manipulation. In 2HC, the two-mana cost allows deploying it the same turn a tutor finds it." },
  { name: "Temporal Trespass", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Delve makes this effectively free in a long game with a stocked graveyard. A zero-cost extra turn in the mid-to-late game is a reliable game-ending play — doubly so in 2HC where both players act during the bonus turn." },
  { name: "Time Sieve", type: "Artifact", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Sacrifice five artifacts to take an extra turn. Trivially repeatable with Thopter Foundry. A two-card infinite turn combo that costs minimal mana once the token engine is established." },
  { name: "Time Stretch", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Grants two extra turns. With both teammates acting in each extra turn, this produces four full turns of combined action — an almost certain game-ending spell from the turn it resolves." },
  { name: "Time Walk", type: "Sorcery", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Take an extra turn for just two mana — the cheapest extra turn spell ever printed. In 2HC, one extra turn means both teammates untap and act simultaneously, providing the equivalent of two full extra turns for just two mana." },
  { name: "Time Warp", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Five mana, no conditions, no drawback — the quintessential extra turn benchmark. Easily looped through Archaeomancer-style effects. In 2HC, both players untapping and acting doubles the advantage of every single casting." },
  { name: "Timesifter", type: "Artifact", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "At each upkeep, each player reveals their top card and the highest CMC gets an extra turn. With topdeck manipulation, the casting team reliably wins the trigger every single upkeep — generating automatic extra turns every round until the game ends." },
  { name: "Timestream Navigator", type: "Creature — Human Pirate", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "City's blessing-enabled activated ability grants an extra turn. The repeatable nature — activate, extra turn, bounce, replay — creates an infinite turn loop with any bounce effect and a cost reducer." },
  { name: "Twice Upon a Time // Unlikely Meeting", type: "Instant — Adventure", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "A five-mana extra turn spell with a useful adventure side. The modal nature makes it never a dead card — and in 2HC the extra turn side produces both teammates untapping for a full additional simultaneous turn." },
  { name: "Ugin's Nexus", type: "Legendary Artifact", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Prevents opponents from taking extra turns; when destroyed, grants an extra turn. In 2HC, engineering its destruction via sacrifice for a free extra turn is a repeatable strategy — while it also acts as a hate piece against other extra turn effects." },
  { name: "Ultimecia, Time Sorceress // Ultimecia, Omnipotent", type: "Legendary Creature — Human Wizard", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Copies spells opponents cast and enables time-based triggers. In 2HC, copying powerful opposing spells while being protected by a teammate creates a free-value engine nearly impossible to stop without coordinated instant-speed interaction from both opponents simultaneously." },
  { name: "Walk the Aeons", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Buyback cost of sacrificing three Islands enables looping with land recursion, creating infinite extra turns. Even without buyback it's a clean five-mana extra turn — and in 2HC the infinite loop is achieved faster with a teammate accelerating the Island count." },
  { name: "Wanderwine Prophets", type: "Creature — Merfolk Wizard", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Grants an extra turn whenever it deals combat damage to a player. With any evasion enabler, this repeatedly triggers — locking opponents out of the game through chained turns, particularly easy to protect in 2HC with a teammate holding interaction." },
  { name: "Warrior's Oath", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "One red mana for an extra turn. Trivially negated by Final Fortune combo pieces or simply winning within the extra turn — overwhelmingly likely in 2HC given both teammates' combined board state during the bonus turn." },
  { name: "Wormfang Manta", type: "Creature — Nightmare Fish Beast", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Skip a turn when it enters; take an extra turn when it leaves. Exploited by sacrifice, blink, or bounce effects to take an extra turn immediately without ever suffering the skip — on-demand extra turns with a teammate providing the sacrifice outlet." },
  { name: "Expropriate", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — council's dilemma", reason: "Council's dilemma where opponents choose extra turn or their permanent. In 2HC, three opponents voting generates at minimum one extra turn and usually stolen permanents. With a full table, routinely produces two or three extra turns plus multiple thefts." },

  { name: "Stitch in Time", type: "Sorcery", cat: "extra-turn", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Flip a coin — on heads, take an extra turn. In 2HC, with any coin manipulation effect such as Krark's Thumb, the expected value of each casting approaches a full extra team turn. Even without manipulation, the 50% chance of a game-winning extra turn at three mana is well above rate." },

  // ── TUTORS ─────────────────────────────────────────────────────

  { name: "Academy Rector", type: "Creature — Human Cleric", cat: "tutor", pill: "pill-edh", origin: "Banned in 2HC", reason: "When it dies, tutors any enchantment directly into play for free. Sacrificing it with any free outlet instantly deploys Omniscience, or any other game-ending enchantment at zero mana cost. In 2HC, a teammate providing sacrifice support makes this trivially consistent on turns 2–3." },
  { name: "Beseech the Mirror", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "The bargain cost lets you cast any found card with CMC 4 or less for free — effectively a two-mana unconditional tutor that casts its target immediately, collapsing two actions into one turn." },
  { name: "Birthing Pod", type: "Artifact", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Repeatable sacrifice-and-tutor up the mana curve. Each activation deploys any creature at CMC+1. Over multiple turns, assembles any creature combo chain. In 2HC the Pod belongs to one player but the assembled combo wins for the entire team." },
  { name: "Buried Alive", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Three mana puts up to three creatures directly into the graveyard. Assembles complete Reanimator or Protean Hulk combo lines in one spell. In 2HC, a teammate providing reanimation makes this effectively a three-mana 'deploy any creature.'" },
  { name: "Chord of Calling", type: "Instant", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Convoke creature tutor putting the found creature directly into play. With a full board the effective mana cost drops to nearly zero. In 2HC, both teammates contributing creatures to convoke makes this essentially free for almost any CMC target." },
  { name: "Defense of the Heart", type: "Enchantment", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "If an opponent controls three or more creatures, at your upkeep tutor two creatures directly into play for free. In 2HC, opponents regularly hit three creatures by turn two — deploying a two-creature combo for free as early as turn three." },
  { name: "Demonic Consultation", type: "Instant", cat: "tutor", pill: "pill-edh", origin: "Banned — combo tutor", reason: "Pairs with Thassa's Oracle as a two-card instant-win combo requiring only one blue and one black mana. One of the most consistent and efficient combo kills in the history of Commander." },
  { name: "Demonic Counsel", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Unconditional tutor searching the library for any card. In 2HC, both players executing a unified game plan make any unconditional library search disproportionately powerful — finding any combo piece, lock, or win condition on demand." },
  { name: "Demonic Tutor", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Two-mana unconditional tutor putting any card directly into hand. The gold standard of tutors. In 2HC, both players having access to their entire library on demand compounds the inherent advantage of drawing twice as many cards per turn cycle." },
  { name: "Diabolic Intent", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Two-mana tutor requiring a creature sacrifice. In 2HC, a teammate running a token strategy provides endless sacrifice fodder — making this functionally a two-mana Demonic Tutor for the entire game." },
  { name: "Eladamri's Call", type: "Instant", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Instant-speed tutor putting any creature directly into hand — bypassing topdeck interaction entirely. Provides guaranteed access to any creature in the deck at instant speed." },
  { name: "Eldritch Evolution", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Sacrifice a creature to tutor one with CMC up to two more directly into play. Efficiently climbs the mana curve and instantly deploys a game-ending threat from any expendable creature." },
  { name: "Enlightened Tutor", type: "Instant", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Instant-speed tutor for any artifact or enchantment. Finds Sol Ring, Necropotence, or any game-defining permanent at instant speed. In 2HC, finding a lock piece benefits both teammates' positions simultaneously." },
  { name: "Entomb", type: "Instant", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "One-mana instant putting any card from library directly into the graveyard. In 2HC with a reanimation-focused teammate, this is effectively a one-mana 'put any creature into play' at instant speed." },
  { name: "Finale of Devastation", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Scales from creature tutor to a game-winning anthem at X=10. At high mana it simultaneously finds any creature and gives all creatures +X/+X and haste — a single spell that tutors a win condition and enables lethal combat damage in the same resolution." },
  { name: "Gamble", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "One-mana tutor for any card with a random discard after. In 2HC where both players draw every turn cycle, the discard cost is negligible — effectively a one-mana unconditional tutor in the mid-game." },
  { name: "Gifts Ungiven", type: "Instant", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Searches the library for up to four cards; an opponent distributes them into two piles and you keep one. In 2HC with a teammate holding the right setup, all four targets are synergistic or redundant — guaranteeing the casting team gets what they need regardless of how the piles are split." },
  { name: "Green Sun's Zenith", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Shuffles back into the library making it un-millable — effectively a recurring tutor. Puts any green creature directly into play, enabling repeated access to Dryad Arbor at one mana or any green combo creature at any cost." },
  { name: "Hermit Druid", type: "Creature — Human Druid", cat: "combo", pill: "pill-edh", origin: "Banned — library mill combo", reason: "In a deck with zero basics, mills the entire library instantly — enabling Thassa's Oracle or Laboratory Maniac as an immediate win from a two-card, two-mana combination requiring no battlefield setup." },
  { name: "Imperial Seal", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "A sorcery-speed Vampiric Tutor placing any card on top of the library for one mana. In 2HC with both players drawing each turn, the top-of-library placement is exploited immediately — a one-mana unconditional tutor." },
  { name: "Intuition", type: "Instant", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Instant-speed tutor giving an opponent a false choice between three found cards. Designed so all three targets are synergistic — making the choice irrelevant. Instant speed allows tutoring on the opposing team's end step." },
  { name: "Lim-Dûl's Vault", type: "Instant", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Instant-speed repeating library dig paying life to arrange the top five cards. Life payments are negligible against 60 shared life. Instant-speed setup during opponents' end steps provides guaranteed card placement for near-zero cost." },
  { name: "Mystical Tutor", type: "Instant", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Instant-speed tutor for any instant or sorcery. In 2HC, tutoring on the opposing team's end step before the team's critical turn creates an uninterruptible game-winning line." },
  { name: "Natural Order", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Sacrifice any green creature to put any green creature directly into play. The sacrifice cost is trivially satisfied by a 1/1 token, instantly deploying Protean Hulk or any game-ending green creature regardless of its actual cost." },
  { name: "Neoform", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Two-mana sacrifice-and-tutor deploying any creature at CMC+1 directly into play — the most mana-efficient creature tutor in the format and a reliable one-card combo setup finding Protean Hulk from nearly any two-drop." },
  { name: "Pattern of Rebirth", type: "Enchantment — Aura", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "When the enchanted creature dies, tutor any creature directly into play. Attaching this to a sacrifice outlet creature immediately sets up a free tutor for Protean Hulk — a two-card instant win line requiring only one creature and any sacrifice effect." },
  { name: "Personal Tutor", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "One-mana tutor for any sorcery placed on top of library. Primarily finds Time Warp effects or other game-warping sorceries. Cast the turn before the team's critical turn to guarantee the right sorcery is drawn on demand." },
  { name: "Razaketh, the Foulblooded", type: "Legendary Creature — Demon", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Pay 2 life and sacrifice a creature to tutor any card to hand. Against 60 shared life the payment is irrelevant, and tokens provide free sacrifice fodder. Each activation tutors unconditionally — assembling any combo in two or three activations." },
  { name: "Scheming Symmetry", type: "Sorcery", cat: "tutor", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Both players tutor a card to the top of their library. The 'symmetry' is false — the casting team chose when to play this. Opponents receive their tutor too late to matter, while the casting team tutors at the exact moment they're set up to win." },
  { name: "Survival of the Fittest", type: "Enchantment", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Repeatable creature filtering — discard a creature to tutor any creature to hand. In 2HC, a teammate providing discard fodder allows Survival to activate every turn, systematically tutoring the entire creature combo chain over two to three turns." },
  { name: "Sylvan Tutor", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "One-mana creature tutor to top of library. Cast the turn before the team's critical turn to guarantee the right creature is drawn on demand — a one-mana setup for any creature-based win condition." },
  { name: "Tainted Pact", type: "Instant", cat: "tutor", pill: "pill-edh", origin: "Banned — combo tutor", reason: "Pairs with Thassa's Oracle as a two-card instant win identical in function to Demonic Consultation. In Commander's near-singleton environment, this frequently exiles very few cards while finding any card in the deck." },
  { name: "Time of Need", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Two-mana tutor for any legendary creature. In Commander where the game revolves around legendaries, this finds any game-winning legendary threat at minimal cost while a teammate is already set up to support it." },
  { name: "Traverse the Ulvenwald", type: "Sorcery", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "One-mana land tutor early; unconditional permanent tutor post-delirium. Delirium is trivially achieved by turn four in Commander — making this a one-mana unconditional tutor in the mid-to-late game for any permanent." },
  { name: "Vampiric Tutor", type: "Instant", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "One-mana instant-speed tutor to the top of the library. The life payment is negligible against a 60-life pool. Team coordination — draw the tutored card while a teammate protects the game state — makes this devastating at instant speed." },
  { name: "Wishclaw Talisman", type: "Artifact", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Three charges of unconditional tutoring, passing control after each use. In 2HC, a teammate can flicker or bounce it before an opponent uses their stored charge — providing multiple unconditional tutors while denying opponents access to any." },
  { name: "Worldly Tutor", type: "Instant", cat: "tutor", pill: "pill-edh", origin: "Banned — tutor", reason: "Instant-speed creature tutor to the top of library. Finds Protean Hulk, Thassa's Oracle, or any combo creature on demand — with instant speed allowing tutoring on opponents' end steps before the team's critical turn." },
  { name: "Summoner's Pact", type: "Instant", cat: "tutor", pill: "pill-edh", origin: "Banned — free tutor", reason: "Zero-mana instant-speed tutor for any green creature, paying four green next turn or losing. In 2HC, the delayed payment is trivially handled through team resources — functionally a free unconditional green creature tutor finding any combo piece." },

  // ── FAST MANA ──────────────────────────────────────────────────

  { name: "Grim Monolith", type: "Artifact", cat: "fast-mana", pill: "pill-edh", origin: "Banned — fast mana / infinite combo", reason: "Costs two, taps for three colorless, untaps for four. With Power Artifact produces infinite colorless mana. Even standalone it's a massive accelerant that funds any game-ending spell several turns ahead of normal development." },
  { name: "Ancient Tomb", type: "Land", cat: "fast-mana", pill: "pill-edh", origin: "Banned — fast mana", reason: "Produces two colorless mana at the cost of 2 life per tap. Against a shared 60-life total the payment is negligible. Two free mana on turn one accelerates commanders and combo pieces multiple turns ahead of opponents developing normally." },
  { name: "Basalt Monolith", type: "Artifact", cat: "combo", pill: "pill-edh", origin: "Banned — fast mana / infinite combo", reason: "Taps for three colorless, untaps for three. With Rings of Brighthearth, Kinnan, Zirda and many others, produces infinite colorless mana — a two-card combo. Even standalone it's a powerful accelerant leading to game-ending plays several turns ahead of the curve." },
  { name: "Black Lotus", type: "Artifact", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Sacrifice to add three mana of any color. The most broken card ever printed — a zero-cost accelerant that pushes any game plan three full turns ahead on turn one. In 2HC, enabling a teammate's early commander cast or combo piece is catastrophic for both opponents." },
  { name: "Channel", type: "Sorcery", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Convert life into colorless mana at one-for-one. Against a 60-life shared pool a player can convert up to 59 life into 59 mana in a single card. Combined with any Fireball effect, this wins the game on turn one with just two cards in hand." },
  { name: "Chrome Mox", type: "Artifact", cat: "fast-mana", pill: "pill-edh", origin: "Banned — fast mana", reason: "Zero-cost colored mana at the cost of a card from hand. In 2HC, the card disadvantage is offset by both players drawing every turn cycle, maintaining near-constant hand parity while accelerating mana on critical turns." },
  { name: "Dockside Extortionist", type: "Creature — Goblin Pirate", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Creates a Treasure for each artifact and enchantment opponents control. In 2HC with four players developing boards, a mid-game Dockside routinely generates 10–16 Treasures in one cast — a mana burst so large it enables any combo or game-winning play immediately." },
  { name: "Fastbond", type: "Enchantment", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Play any number of lands per turn, paying 1 life per extra land. Against a 60-life shared pool the cost is negligible. Combined with any land-fetch effect, the casting team deploys their entire land hand on turn one — accelerating by five or more turns immediately." },
  { name: "Gaea's Cradle", type: "Legendary Land", cat: "fast-mana", pill: "pill-edh", origin: "Banned — fast mana", reason: "Produces mana equal to the number of creatures you control. In 2HC, a teammate flooding the board first makes Cradle produce enormous mana the very first turn it's in play — often 6–10 mana from a single land." },
  { name: "Jeweled Lotus", type: "Artifact", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Sacrifice to add three mana of any color restricted to casting your commander. A zero-cost three-mana accelerant for the most important spell in the format. In 2HC, enabling a teammate's turn-one commander cast gives the entire team an overwhelming head start on the defining resource in Commander." },
  { name: "Library of Alexandria", type: "Land", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Tap to draw a card when you have exactly seven cards in hand. In Commander where players routinely maintain large hands, this provides a free card draw every turn with no mana cost — compounding card advantage through a permanent opponents have no straightforward way to interact with." },
  { name: "Lion's Eye Diamond", type: "Artifact", cat: "fast-mana", pill: "pill-edh", origin: "Banned — fast mana", reason: "Three free mana at the cost of your entire hand, usable as an instant before any spell resolves. Effectively a Black Lotus in any storm or combo deck where the hand empties naturally." },
  { name: "Lotus Petal", type: "Artifact", cat: "fast-mana", pill: "pill-edh", origin: "Banned — fast mana", reason: "Zero-cost one-time source of any color of mana. Enables turn-one plays otherwise impossible. In 2HC, both players simultaneously deploying fast mana on turn one creates a combined opening tempo that no fair mana development can match." },
  { name: "Mana Crypt", type: "Artifact", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Zero cost, produces two colorless mana every turn with a 50% chance of dealing 3 damage. Against 60 shared life the damage is negligible. A free two-mana rock on turn one accelerates the team by multiple turns while providing permanent mana advantage for the entire game." },
  { name: "Mana Vault", type: "Artifact", cat: "fast-mana", pill: "pill-edh", origin: "Banned — fast mana", reason: "One mana for a permanent source of three colorless. The life loss from failing to untap is negligible against 60 shared life — effectively negative-two mana the turn it's played, enabling turn-one game-warping plays." },
  { name: "Mishra's Workshop", type: "Land", cat: "fast-mana", pill: "pill-edh", origin: "Banned — fast mana", reason: "Produces three colorless mana restricted to artifact spells — effectively a Black Lotus that never leaves play in an artifact Commander deck. Enables deploying multiple expensive artifacts per turn from turn one." },
  { name: "Mox Amber", type: "Legendary Artifact", cat: "fast-mana", pill: "pill-edh", origin: "Banned — fast mana", reason: "Produces free mana matching any legendary creature or planeswalker you control. In Commander, your commander is always available — making this a zero-cost mana rock matching your deck's colors from the very first turn." },
  { name: "Mox Diamond", type: "Artifact", cat: "fast-mana", pill: "pill-edh", origin: "Banned — fast mana", reason: "Discard a land to produce one mana of any color for free. The land-discard cost is irrelevant with abundant land drops in Commander or a teammate running land recursion — effectively a zero-cost colored mana rock." },
  { name: "Mox Emerald", type: "Artifact", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Zero cost artifact producing one green mana — a free mana rock that never costs anything to deploy. Provides permanent mana acceleration from turn one. In 2HC, multiple Moxen in one hand enable both players to cast their full game plan several turns ahead of opponents." },
  { name: "Mox Jet", type: "Artifact", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Zero cost artifact producing one black mana. A free permanent mana source from turn one. Collectively the Moxen enable turn-one plays three to four turns ahead of normal Commander pacing — fundamentally invalidating the format's intended curve." },
  { name: "Mox Opal", type: "Legendary Artifact", cat: "fast-mana", pill: "pill-edh", origin: "Banned — fast mana", reason: "Metalcraft-enabled free colored mana trivially enabled in artifact decks by turn one. A zero-cost mana rock that turns on early and never turns off in any artifact-focused Commander strategy." },
  { name: "Mox Pearl", type: "Artifact", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Zero cost artifact producing one white mana. A free permanent mana source from turn one. Any white commander ability or protection spell available one turn earlier changes the board state irrevocably in a format where tempo defines the winner." },
  { name: "Mox Ruby", type: "Artifact", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Zero cost artifact producing one red mana. A free permanent mana source from turn one. Red's burn and haste creatures become available a full turn ahead of schedule — in Commander, one free mana changes every early interaction window." },
  { name: "Mox Sapphire", type: "Artifact", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Zero cost artifact producing one blue mana. A free permanent mana source from turn one. Counterspells and draw spells available one turn earlier than opponents can answer them define the entire early game — blue benefits most from any free mana in the format." },
  { name: "Primeval Titan", type: "Creature — Giant", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Fetches two lands on ETB and on each attack. Tutoring dual lands, utility lands, or combo lands twice on entry immediately enables any mana combination. In 2HC, a teammate providing blink or extra attack steps turns Primeval Titan into an unstoppable land chain that outramps any possible response." },
  { name: "Rofellos, Llanowar Emissary", type: "Legendary Creature — Elf Druid", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Adds one green mana for each Forest you control. As a commander, Rofellos taps for 5–7 green mana by turn three in any typical green deck — an explosive mana engine that puts the casting team's game plan years ahead of any opponent's ability to catch up." },
  { name: "Sol Ring", type: "Artifact", cat: "fast-mana", pill: "pill-edh", origin: "Banned in 2HC", reason: "The most format-defining mana rock in Commander. In 2HC with both players potentially running Sol Ring, the combined mana advantage on turn one creates an insurmountable tempo gap. Banned to prevent mandatory ring-or-lose opening hands." },
  { name: "Time Vault", type: "Artifact", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Untap by skipping your next turn; tap to take an extra turn. Combined with any untap effect such as Voltaic Key, this produces infinite extra turns from two cards. In 2HC, infinite extra turns means both teammates take infinite turns simultaneously — an immediate and unresolvable game win." },
  { name: "Tolarian Academy", type: "Legendary Land", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Produces one blue mana per artifact you control. In any artifact Commander deck, Tolarian Academy taps for 5–10 blue mana by turn three — enabling any blue spell or combo piece at a fraction of its intended cost, with zero drawback." },

  // ── BIG LIFE TOTAL ─────────────────────────────────────────────

  { name: "Ad Nauseam", type: "Instant", cat: "big-life", pill: "pill-edh", origin: "Banned — combo enabler", reason: "Reveals and draws cards paying life equal to each card's CMC. Draws the entire library in low-curve combo builds. Against a shared 60-life pool, paying life to draw 20+ cards is dramatically safer than in any solo format — instantly assembling any combo with no meaningful life cost." },
  { name: "Aetherflux Reservoir", type: "Artifact", cat: "big-life", pill: "pill-edh", origin: "Banned — alternate win condition", reason: "Deals 50 damage to a target by paying 50 life. Teams starting at 60 life enables the damage ability immediately." },
  { name: "Bolas's Citadel", type: "Legendary Artifact", cat: "big-life", pill: "pill-edh", origin: "Banned — infinite combo", reason: "Play cards from the top of the library paying life instead of mana. Against a 60-life pool, sustaining Citadel-fueled casting is viable far longer than in solo formats. Chains naturally into Aetherflux Reservoir for a near-unstoppable kill engine." },
  { name: "Doom Whisperer", type: "Creature — Nightmare Demon", cat: "big-life", pill: "pill-edh", origin: "Banned — combo enabler", reason: "Pay 2 life to surveil 2 — repeatable library manipulation at trivial cost against a 60-life pool. Enables rapid filtering to find combo pieces or precisely engineering Thassa's Oracle lines." },
  { name: "Felidar Sovereign", type: "Creature — Cat Beast", cat: "big-life", pill: "pill-edh", origin: "Banned — alt win condition", reason: "Win the game at upkeep if you have 40 or more life. In 2HC with a shared pool starting at 60, any life gain strategy trivially maintains this threshold. Lifegain commanders make this an automatic win by turn 5–6 with no combat required." },
  { name: "Hatred", type: "Instant", cat: "big-life", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Pay X life to give target creature +X/+0 and trample until end of turn. Against a shared 60-life pool, a player can funnel up to 59 life into a single attack, dealing lethal damage in one swing at a fraction of the cost compared to solo Commander. The doubled life total turns this into a one-card, one-attack win condition requiring almost no setup." },
  { name: "Necrodominance", type: "Enchantment", cat: "big-life", pill: "pill-edh", origin: "Banned — draw engine", reason: "Draw up to five cards each end step by paying life. Against a shared 60-life pool, paying 5 life per turn to draw five cards is sustainable for 12 full turns at full life — creating an overwhelming and uninterruptible card advantage engine." },
  { name: "Necrologia", type: "Instant", cat: "big-life", pill: "pill-edh", origin: "Banned — draw engine", reason: "Instant-speed mass draw at the cost of life. Against a 60-life pool, drawing 30 cards at instant speed before the team's turn is a near-guaranteed win setup at minimal cost." },
  { name: "Necropotence", type: "Enchantment", cat: "big-life", pill: "pill-edh", origin: "Banned — draw engine", reason: "Pay 1 life per card drawn at end of turn. Against a 60-life pool, drawing 20+ cards per turn while a teammate protects the board is an insurmountable advantage that buries opponents in card quantity." },
  { name: "Test of Endurance", type: "Enchantment", cat: "big-life", pill: "pill-edh", origin: "Banned — alt win condition", reason: "Win the game at upkeep if you have 50 or more life. Starting at 60 shared life, this wins immediately in the absence of life loss. Even with moderate damage taken, minor life gain from either teammate triggers an immediate team win." },
  { name: "Treasonous Ogre", type: "Creature — Ogre Shaman", cat: "big-life", pill: "pill-edh", origin: "Banned — mana/life combo", reason: "Pay 3 life for one red mana. Against a 60-life pool, converting 30 life into 10 red mana on a critical turn enables casting enormous X-spells or fully funding a combo that wins immediately." },
  { name: "Yawgmoth's Bargain", type: "Enchantment", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Pay one life to skip your draw and draw an extra card, at any time. Against 60 shared life, a team can draw 50+ cards over a few turns for negligible cost. Effectively an enchantment that draws the entire library — assembling any combo in one turn with no hand size restriction." },

  // ── LIFE MANIPULATION ──────────────────────────────────────────

  { name: "Biorhythm", type: "Sorcery", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Sets each player's life total to the number of creatures they control. In 2HC with a shared life pool, a team with any token generator can set both opponents' shared life to a single digit — creating an immediate lethal scenario from almost any board state." },
  { name: "Grievous Wound", type: "Sorcery", cat: "life-manip", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Sets a player's maximum life total to a reduced amount. In 2HC, damaging the enchanted player affects the entire shared life pool. Combined with any cheap source of repeatable damage from both players, it reprensents way too much damage for a 5-mana card." },
  { name: "Havoc Festival", type: "Enchantment", cat: "life-manip", pill: "pill-edh", origin: "Banned — life drain", reason: "Players can't gain life and each player loses half their life rounded up at each of their upkeeps. In 2HC, both players are affected in succession, which represents a 75% life swing in one turn." },
  { name: "Heartless Hidetsugu", type: "Legendary Creature — Ogre Shaman", cat: "life-manip", pill: "pill-edh", origin: "Banned — targeted life halving", reason: "Tap to deal damage equal to half each opponent's life total rounded down. In 2HC, both players are dealt damage at the same time when the ability resolves, which means that any team with an even life total dies immediately." },
  { name: "Magister Sphinx", type: "Artifact Creature — Sphinx", cat: "life-manip", pill: "pill-edh", origin: "Banned — alt win condition", reason: "Sets target player's life total to 10 on entry. In 2HC, targeting any opposing player sets the entire team's shared life to 10 regardless of their starting total. Blink or reanimation repeatedly applies this, keeping opponents at 10 with no recovery possible." },
  { name: "Scourge of the Skyclaves", type: "Creature — Demon", cat: "life-manip", pill: "pill-2hg", origin: "Banned — 2HG specific", reason: "When cast with kicker, it reduces all teams' life totals by 75% when it enters, as both players are affected successively." },
  { name: "Secret of Bloodbending", type: "Sorcery", cat: "extra-turn", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Gains control of a player's life total changes for a turn. In 2HC, controlling how life changes resolve for one opposing player affects the entire shared pool — inverting the life economy completely. Life drain directed at one opponent becomes life gain for the casting team." },
  { name: "Sorin Markov", type: "Legendary Planeswalker", cat: "life-manip", pill: "pill-edh", origin: "Banned — alt win condition", reason: "Second ability sets target player's life to 10. In 2HC, targeting any opposing player sets the entire team's shared pool to 10 regardless of their starting total — a 50-life swing in a single planeswalker activation. Furthermore, its ultimate enables a team to control the entire opposing team, as turns and phases are shared in 2HC." },
  { name: "The Legend of Kuruk // Avatar Kuruk", type: "Legendary Enchantment", cat: "extra-turn", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "A saga that generates mana and scales with creature counts across its chapters. In 2HC, both teammates' combined creature counts feed the saga's scaling — producing disproportionate mana and value per chapter compared to any solo-format equivalent." },
  { name: "Tree of Perdition", type: "Creature — Plant", cat: "life-manip", pill: "pill-edh", origin: "Banned — alt win condition", reason: "Tap to exchange its toughness (13) with target opponent's life total. In 2HC, this sets the entire team's shared life to 13. This can put the opposing team at lethal range in a single tap activation, and can be lethal when combined with toughness-reducing effects." },

  // ── COMBO ──────────────────────────────────────────────────────

  { name: "Chain of Smog", type: "Sorcery", cat: "combo", pill: "pill-edh", origin: "Banned — infinite combo", reason: "Creates an infinite loop with Witherbloom Apprentice or Professor Onyx, that drains all opponents to zero. A two-card, two-mana instant win requiring no board setup beyond two specific cards." },
  { name: "Cloud of Faeries", type: "Creature — Faerie", cat: "combo", pill: "pill-edh", origin: "Banned — infinite mana", reason: "Untaps two lands on entry. With cost-reduction effects becomes a zero-mana creature generating net mana on replay — creating infinite mana and infinite ETB triggers in bounce or storm shells." },
  { name: "Dualcaster Mage", type: "Creature — Human Wizard", cat: "combo", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Flash creature that copies a spell on entry. It can generate an infinite number of copies with any instant or sorcery that creates a copy with haste, a fast combo that can occur with almost no setup and without warning." },
  { name: "Flash", type: "Instant", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Put any creature from hand into play at instant speed, paying the difference or paying nothing and returning the creature to hand. Enables a zero-mana instant-speed deployment of Protean Hulk — triggering an unstoppable graveyard combo chain before any opponent can respond." },
  { name: "Food Chain", type: "Enchantment", cat: "combo", pill: "pill-edh", origin: "Banned — infinite mana", reason: "With any creature castable from exile, creates infinite mana for creature spells — a two-card infinite mana engine enabling infinite ETBs and unlimited creature deployment." },
  { name: "Griselbrand", type: "Legendary Creature — Demon", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Pay 7 life to draw 7 cards, repeatable as many times as you have life. Against 60 shared life, drawing 49 cards for 49 life is easily survivable. Reanimated on turn two, this draws essentially the entire deck in one activation — enabling any combo immediately with no counterplay." },
  { name: "Isochron Scepter", type: "Artifact", cat: "misc", pill: "pill-edh", origin: "Banned — infinite combo", reason: "With Dramatic Reversal and sufficient mana rocks produces infinite mana. With Silence, permanently locks opponents out of spellcasting. A two-card infinite combo engine with dozens of viable imprint targets." },
  { name: "Mana Drain", type: "Instant", cat: "misc", pill: "pill-edh", origin: "Banned — free mana counter", reason: "Counters any spell and adds its mana cost to your pool next main phase. A free counter that converts opponents' spells into your mana. In 2HC, countering a five-mana spell and generating five free mana the following turn creates enormous compound advantage." },
  { name: "Nadu, Winged Wisdom", type: "Legendary Creature — Bird Wizard", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Whenever a creature you control is targeted by a spell or ability, draw a card and put a land from the top of your library into play. In 2HC, both teammates targeting their own creatures chains unlimited free draws and land drops in a single turn — assembling any combo with no counterplay window." },
  { name: "Oath of Druids", type: "Enchantment", cat: "tutor", pill: "pill-edh", origin: "Banned — library cheat", reason: "At each player's upkeep, if an opponent controls more creatures, flip until finding a creature and put it into play. In 2HC, opponents almost always have more creatures — so Oath triggers every turn, freely deploying any creature from the library every single upkeep." },
  { name: "Painter's Servant", type: "Artifact Creature — Scarecrow", cat: "combo", pill: "pill-edh", origin: "Banned — lock combo", reason: "Makes all cards a chosen color. With Grindstone, mills any player's entire library in one activation — a two-card instant-mill combo requiring minimal mana and no other prerequisites." },
  { name: "Peregrine Drake", type: "Creature — Drake", cat: "combo", pill: "pill-edh", origin: "Banned — infinite mana", reason: "Untaps five lands on entry. In blink, copy or bounce decks, can generate overwhelming quantities of mana very quickly and has multiple infinite combo applications." },
  { name: "Prophet of Kruphix", type: "Creature — Human Wizard", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Untaps all creatures and lands during each other player's untap step and gives all creatures flash. In 2HC with three additional untap phases per turn cycle, the casting team effectively never taps out — holding full mana for counterspells while casting creatures at instant speed every phase." },
  { name: "Protean Hulk", type: "Creature — Beast", cat: "combo", pill: "pill-edh", origin: "Banned — instant win combo", reason: "When it dies, tutors up to six CMC worth of creatures directly into play. Any sacrifice outlet immediately deploys a complete combo board. In 2HC, a teammate providing a free sacrifice outlet makes Hulk a one-card win from virtually any game state." },
  { name: "Recurring Nightmare", type: "Enchantment", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Sacrifice a creature and pay mana to reanimate any creature from the graveyard — the enchantment returns to hand and cannot be countered. In 2HC, this cycling reanimation engine loops any graveyard creature endlessly, combining both players' graveyards to assemble any enter-the-battlefield combo chain." },
  { name: "Thassa's Oracle", type: "Creature — Merfolk Wizard", cat: "combo", pill: "pill-edh", origin: "Banned — instant win combo", reason: "Combined with Demonic Consultation or Tainted Pact, this is a two-card instant-win requiring only one blue and one black mana. One of the most consistent and efficient combo kills in the history of Commander." },
  { name: "Tinker", type: "Sorcery", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Sacrifice any artifact to tutor any artifact from the library directly into play. A Sol Ring can be sacrificed to deploy Blightsteel Colossus or any game-ending artifact for just two mana. In 2HC, a teammate holding protection ensures the winning artifact resolves and attacks the same turn it enters." },
  { name: "Underworld Breach", type: "Enchantment", cat: "combo", pill: "pill-edh", origin: "Banned — infinite combo", reason: "Recasts instants, sorceries, and creatures from the graveyard by exiling other cards. Enables looping through the entire deck with Brain Freeze or Wheel effects — a flexible infinite combo engine with multiple convergent lines." },
  { name: "Upheaval", type: "Sorcery", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Return all permanents to their owners' hands. Cast with mana floating, the casting team immediately redeploys their most important permanents while both opponents must rebuild their entire boards from scratch — a six-mana asymmetric reset that hands the casting team an insurmountable advantage." },
  { name: "Walking Ballista", type: "Artifact Creature — Construct", cat: "combo", pill: "pill-edh", origin: "Banned — combo win condition", reason: "Universal game-ender for any combo producing infinite colorless mana. Basalt Monolith, Grim Monolith, Food Chain, and dozens of other combos directly funnel into Walking Ballista to instantly deal lethal damage to all opposing players at once." },

  // ── HARD STAX ──────────────────────────────────────────────────

  { name: "Armageddon", type: "Sorcery", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Destroys all lands. In 2HC, the casting team prepares by floating mana or holding artifact mana sources before casting — both opposing players lose their entire land base simultaneously. Rebuilding from zero mana is catastrophic when the casting team has pre-positioned their resources and both opponents must restart from scratch." },
  { name: "Back to Basics", type: "Enchantment", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Nonbasic lands don't untap. Commander mana bases are predominantly nonbasic — shock lands, fetch lands, and dual lands all fail to untap. In 2HC, this locks both opposing players' mana bases simultaneously while a teammate running basics is completely unaffected, creating a permanent asymmetric mana lock." },
  { name: "Cataclysm", type: "Sorcery", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Each player keeps only one land, artifact, creature, and enchantment, sacrificing the rest. In 2HC, the casting team pre-selects their most valuable permanent of each type before resolving — both opposing teams are forced to dismantle their boards simultaneously, resetting the game to a state the casting team has fully prepared for." },
  { name: "Drannith Magistrate", type: "Creature — Human Wizard", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Prevents casting spells from anywhere other than hand — including the Command Zone. Permanently prevents casting commanders, the defining mechanic of the format. In 2HC, one player deploying this while a teammate protects it locks both opposing commanders out of the game simultaneously." },
  { name: "Flamescroll Celebrant // Revel in Silence", type: "Creature — Human Shaman", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Opponents must pay 1 mana to activate any activated ability. In 2HC, both opposing players must pay this tax during their shared turn — applying the cost to every Fetch crack, every loyalty activation, every mana rock tap. The cumulative drain creates a severe mana disadvantage for both opponents at once." },
  { name: "Global Ruin", type: "Sorcery", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Each player may keep one land of each basic land type they control, destroying the rest. Commander's heavily nonbasic mana bases survive only partially — players lose all utility lands and dual lands. In 2HC, both opposing players lose their mana fixing simultaneously while a basic-heavy casting team keeps most of their lands." },
  { name: "Humility", type: "Enchantment", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "All creatures lose all abilities and become 1/1s. Shuts down every activated ability, triggered ability, and static ability on every creature simultaneously. In 2HC, a teammate running an artifact- or enchantment-based strategy remains fully functional while every creature-based win condition across both opposing players is permanently neutralized." },
  { name: "Impending Disaster", type: "Enchantment", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "At the beginning of your upkeep, if any player controls seven or more lands, destroy all lands. In 2HC, two players developing lands each turn reaches the threshold rapidly — the casting team can deliberately stall land development to trigger this precisely when opponents are most vulnerable while the casting team holds floating mana." },
  { name: "Jokulhaups", type: "Sorcery", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Destroys all artifacts, creatures, and lands, leaving only enchantments. In 2HC, the casting team plans to retain only enchantment permanents beforehand — both opposing teams lose their entire boardstate simultaneously, leaving the team with the most hand resources in a completely level reset that only the casting team anticipated." },
  { name: "Mycosynth Lattice", type: "Artifact", cat: "hard-stax", pill: "pill-edh", origin: "Banned — lock combo", reason: "Combined with Karn the Great Creator or Null Rod, locks all opponents out of activating any mana abilities. In 2HC, a complete mana lock on both opposing players simultaneously while the casting team is prepared makes this an inescapable prison." },
  { name: "Ravages of War", type: "Sorcery", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Identical to Armageddon — destroy all lands. Having two cards with this exact effect in the format allows any white deck to reliably find and resolve a total land wipe. The redundancy makes Armageddon-style strategies far more consistent and harder to hate out than in solo Commander." },
  { name: "Stasis", type: "Enchantment", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Players skip their untap steps unless Stasis is sacrificed at the beginning of your upkeep. With Forsaken City, Chronatog, or artifact untap effects, the controller maintains Stasis indefinitely for free. In 2HC, both opposing players are permanently locked out of untapping simultaneously while a teammate with artifact mana sources operates freely." },
  { name: "Static Orb", type: "Artifact", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Each player untaps only three permanents during their untap step. In 2HC, both opposing players are restricted to three untaps simultaneously every turn — halving their functional mana and tapped permanents. The casting team, prepared with artifact mana or untap effects, operates normally while both opponents are perpetually throttled." },
  { name: "Strip Mine", type: "Land", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Tap, sacrifice: destroy target land. Free targeted land destruction hitting any land type including basics. In 2HC, destroying a key combo land, mana-fixing land, or utility land from either opposing player costs nothing — providing zero-mana permanent removal of critical lands with no opportunity cost for the casting team." },
  { name: "Sunder", type: "Instant", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Return all lands to their owners' hands at instant speed. In 2HC, both opposing players lose their entire mana base simultaneously at the end of their turn — the casting team holds floating mana and immediately redeploys on their turn while both opponents start with no lands in play and cannot cast anything." },
  { name: "The Tabernacle at Pendrell Vale", type: "Legendary Land", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Each creature must pay one mana or be destroyed at the beginning of its controller's upkeep. In 2HC, both opposing players pay this cumulative tax during their upkeep simultaneously — draining both players' mana bases at once. Creature-heavy strategies collapse under the compounding drain when both opponents must maintain their combined boards." },
  { name: "Wasteland", type: "Land", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Tap, sacrifice: destroy target nonbasic land. Free targeted removal of any nonbasic land with zero mana cost. In 2HC, systematically destroying shock lands, fetch lands, or combo lands from either opposing player is free and requires no mana investment — methodically dismantling both opponents' mana development across the entire game." },
  { name: "Winter Moon", type: "Enchantment", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Nonbasic lands can only be tapped for colorless mana. In 2HC, this collapses both opposing players' heavily nonbasic mana bases to colorless simultaneously — preventing colored spells from being cast using nonbasic sources. A teammate running basic lands or artifact mana remains fully functional while both opponents are locked out of their commanders' color requirements." },
  { name: "Winter Orb", type: "Artifact", cat: "hard-stax", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Players may untap only one land during their untap step. In 2HC, both opposing players are restricted to one land per turn simultaneously — effectively throttling both opponents to one mana per turn for the rest of the game. The casting team, prepared with artifact mana sources or untap effects, maintains full functionality while both opponents operate at near-zero mana." },

  // ── MISC ───────────────────────────────────────────────────────

  { name: "Deflecting Swat", type: "Instant", cat: "misc", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Free redirection of any spell or ability when you control your commander. In 2HC with four commanders on the table, the free-cast condition is almost always met. A teammate providing a spell creates a zero-cost protection window where every threat can be redirected to an opponent." },
  { name: "Fierce Guardianship", type: "Instant", cat: "misc", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Free counter of any noncreature spell when you control your commander. In 2HC, with two players each holding a potential free counterspell, the team creates a wall of free interaction that makes it nearly impossible for opponents to resolve any meaningful spell." },
  { name: "Mindslaver", type: "Legendary Artifact", cat: "misc", pill: "pill-edh", origin: "Banned — control combo", reason: "Activate to control an opponent's entire next turn. In 2HC, taking control of one opposing player's turn means controlling the entire team's turn. Combined with Academy Ruins or any other artifact recursion effect, creates an infinite loop permanently controlling the opposing team." },
  { name: "Pact of Negation", type: "Instant", cat: "misc", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Free counterspell where a teammate can pay the Pact cost from shared team resources — making the lose-the-game clause trivially avoidable. With both players potentially holding free counterspells, the team creates an impenetrable interaction wall at zero cost." },
  { name: "Sensei's Divining Top", type: "Artifact", cat: "misc", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Repeated activations can extend game time considerably. It is also a very cheap combo piece with any effect that enables recasting it from the top of the deck." },
  { name: "Emrakul, the Promised End", type: "Legendary Creature — Eldrazi", cat: "misc", pill: "pill-edh", origin: "Banned — game-winning threat", reason: "When cast, control an opponent's next turn. In 2HC, taking control of one opposing player's turn means controlling the entire team's turn — which is twice as backbreaking as in one-one-one play." },
  { name: "Golos, Tireless Pilgrim", type: "Legendary Artifact Creature — Scout", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Fetches any land on ETB and generates free spells from all players' library tops for five mana. Banned for enabling every five-color strategy with no restriction — any deck could run Golos as a value commander that tutors lands on entry and casts free spells every turn regardless of color identity." },
  { name: "Sundering Titan", type: "Artifact Creature — Golem", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Destroys a land of each basic type on ETB and when leaving play. In 2HC, entering the battlefield strips both opposing players' mana bases simultaneously. Any blink or bounce effect triggers this repeatedly — permanently dismantling both opponents' lands within two to three turns." },
  { name: "The Dominion Bracelet", type: "Legendary Artifact — Equipment", cat: "misc", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Equipped creature has protection from everything opponents control and can't be blocked. In 2HC, equipping a commander grants complete protection and unblockability — dealing unrestricted commander damage every attack. Three attacks from a 7-power commander equals 21 commander damage with zero counterplay possible." },
  { name: "Worst Fears", type: "Sorcery", cat: "misc", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Control target player until end of turn. In 2HC, taking control of one opposing player's turn means controlling the entire team's turn — which is twice as backbreaking as in one-one-one play." },
  { name: "Discontinuity", type: "Instant", cat: "misc", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Ends the current turn, exiling all spells on the stack. Cast during the opposing team's shared turn, this denies both players any spell casting for that entire turn — a two-for-one turn denial creating an uninterruptible window for the casting team." },
  { name: "Hurkyl's Final Meditation", type: "Legendary Sorcery", cat: "misc", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Returns all artifacts, creatures, and enchantments to their owners' hands and grants an extra turn. In 2HC, both opposing players lose their entire board simultaneously while the casting team takes a full extra turn to redeploy their hand into a winning position with both opponents starting from scratch." },
  { name: "Time Stop", type: "Instant", cat: "misc", pill: "pill-edh", origin: "Banned — extra turns (see manifesto)", reason: "Ends the turn immediately, exiling all spells and abilities on the stack. Cast during the opposing team's turn, this denies both players their entire turn while setting up a follow-up extra turn for the casting team." },
  { name: "Silence", type: "Instant", cat: "misc", pill: "pill-2hc", origin: "Banned — 2HC specific", reason: "Each opponent can't cast spells this turn. In 2HC, casting Silence denies the entire opposing team any spell casting — which would be fine to protect a win, and on par with cards such as Voice of Victory — but when cast during the opposing team's upkeep, it basically functions as a one-mana extra turn spell." },

  // ── OFFICIAL ───────────────────────────────────────────────────
  
  { name: "Sylvan Primordial", type: "Creature — Avatar", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Destroys a noncreature permanent for each opponent and ramps a Forest for each one destroyed on ETB. In 2HC, this destroys two key permanents and ramps two Forests on entry. Blinked or reanimated, it recursively strips all key enchantments and artifacts while accelerating past any mana threshold." },
  { name: "Iona, Shield of Emeria", type: "Legendary Creature — Angel", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Name a color on entry — opponents cannot cast spells of that color. In 2HC, naming an opposing commander's primary color locks that player out for the entire game. Reanimated on turn two with Animate Dead, Iona permanently shuts down an entire player's deck with no available counterplay." },
  { name: "Ancestral Recall", type: "Instant", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Draws three cards for a single blue mana — the most efficient draw spell ever printed. In 2HC, paired with a teammate's card-advantage engine, a turn-one Ancestral creates an insurmountable lead that defines the entire game from the very first turn." },
  { name: "Balance", type: "Sorcery", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Each player discards down to the fewest cards, sacrifices excess lands, and sacrifices excess creatures. In 2HC, the casting team prepares by emptying their hands and boards beforehand — then both opponents are stripped of lands, creatures, and cards simultaneously with a single two-mana sorcery." },
  { name: "Chaos Orb", type: "Artifact", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Requires physically dropping the card from height onto the battlefield to destroy any permanents it touches. Banned from all sanctioned Magic play for requiring physical dexterity rather than game decisions — fundamentally incompatible with the rules of Commander." },
  { name: "Falling Star", type: "Sorcery", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Requires physically flipping the card from height onto the battlefield to deal 3 damage to any creatures it touches. Banned from all sanctioned Magic play for requiring physical dexterity — fundamentally incompatible with Commander and any fair play environment." },
  { name: "Leovold, Emissary of Trest", type: "Legendary Creature — Elf Advisor", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Opponents cannot draw more than one card per turn, and any targeting of your permanents draws you a card instead. In 2HC, Leovold locks both opposing players to one draw per turn while providing free card draw for any interaction — a complete information lock the opposing team cannot break." },
  { name: "Lutri, the Spellchaser", type: "Legendary Creature — Otter Wizard", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Banned as a companion only, because in a 100-card singleton format every red-blue deck automatically qualifies for Lutri at zero deck-building cost — a free eighth card in the opening hand that copies any instant or sorcery on ETB with no restriction possible." },
  { name: "Shahrazad", type: "Sorcery", cat: "commander", pill: "pill-edh", origin: "Banned — EDH banned list", reason: "Players play a sub-game of Magic using their current libraries. Banned from all sanctioned play for creating recursive sub-games that cannot be resolved in any reasonable context — fundamentally incompatible with Commander's game structure and time constraints." },

];

const WATCHLIST_CARDS = [

  { name: "Vivi Ornitier",             type: "Legendary Creature — Human Wizard",   cat: "combo",  discuss: "Being watched as a commander. Vivi's spell-based trigger enables a spellslinger engine where a teammate casting instants and sorceries contributes to the same trigger pool — accelerating his damage or copy output at a rate no solo format accounts for. In 2HC the shared turn means both players' casts fire his ability in the same window, compressing his win timeline significantly. Under review for whether the cooperative spell density makes him too consistent as a commander." },

  { name: "Winota, Joiner of Forces",  type: "Legendary Creature — Human Warrior",  cat: "combo",  discuss: "Being watched as a commander. Whenever a non-Human creature attacks, look at the top six cards and put a Human into play with haste for free. In 2HC, both teammates attacking with non-Humans trigger Winota multiple times in the same combat — potentially deploying four to six free Humans with haste in a single attack step. The volume of free bodies created in one swing may be too high for the format's pace. Already banned in Pioneer for similar reasons." },

  { name: "Yuriko, the Tiger's Shadow", type: "Legendary Creature — Human Ninja",   cat: "combo",  discuss: "Being watched as a commander. Yuriko has commander ninjutsu — she enters from the command zone whenever any unblocked creature connects, bypassing the commander tax entirely and making her effectively impossible to permanently answer. Whenever she deals combat damage, each player loses life equal to a revealed card's mana cost and you draw it. In 2HC, this drains both opposing players simultaneously on each hit while drawing cards — a commander that ignores tax, generates inevitability, and is nearly impossible to lock out once a teammate provides any evasion." },

  { name: "Grand Arbiter Augustin IV", type: "Legendary Creature — Human Advisor",  cat: "2hc",   discuss: "Being watched as a commander. He makes white spells cost 1 less, blue spells cost 1 less, and all opponents' spells cost 1 more. In 2HC, both opposing players pay his tax on every spell during their shared turn — effectively doubling the tax pressure compared to solo Commander. Combined with a teammate also running white or blue, the mana discount accelerates both players simultaneously while both opponents are perpetually slowed on every play. Under review for whether this passive double-tax is too oppressive in a cooperative context." },

  { name: "Nature's Rhythm",           type: "Sorcery",                             cat: "land",   discuss: "Under review for its mana acceleration potential in 2HC. Its effect scales with the combined board state of both teammates — in 2HC, threshold conditions for additional value are met far earlier than in solo Commander. Being monitored for whether the ramp output or card advantage it provides breaks the format's intended mana curve when both players are contributing permanents to the trigger condition." },

  { name: "Invasion of Ikoria",        type: "Battle — Siege",                      cat: "tutor",  discuss: "On entry, tutors any non-Human creature from the library to hand — a versatile one-card tutor for any combo piece or finisher. In 2HC, a teammate can immediately attack the Battle and flip it, deploying its back face in the same turn the first player tutored their piece. The combination of instant creature tutor plus a powerful flip trigger accessible in one team turn creates a two-for-one play that's very difficult to disrupt without coordinated instant-speed interaction from both opponents." },

  { name: "Transmute Artifact",        type: "Instant",                             cat: "tutor",  discuss: "Sacrifice an artifact to tutor any artifact of equal or greater mana cost directly into play. In 2HC, any expendable mana rock can be sacrificed to immediately deploy any game-ending artifact — effectively a free deployment of Blightsteel Colossus, Darksteel Forge, or any combo piece at a fraction of its real cost. Under discussion for whether its zero-extra-mana artifact deployment is too efficient when a teammate holds protection to ensure the target resolves." },

  { name: "Simian Spirit Guide",       type: "Creature — Ape Shaman",               cat: "land",   discuss: "Exile from hand to add one red mana — a free mana source banned in Modern for enabling turn-one plays that bypass normal development. In 2HC, both players potentially holding Spirit Guides in their opening hands creates a combined turn-one tempo that compresses the early game dramatically. Being monitored alongside Elvish Spirit Guide for whether zero-cost mana from the opening hand enables starts that are too far ahead of what fair development can answer." },

  { name: "Elvish Spirit Guide",       type: "Creature — Elf Shaman",               cat: "land",   discuss: "Exile from hand to add one green mana — functionally identical to Simian Spirit Guide. In 2HC, green's already high ramp density combined with a free mana source on the opening hand means the casting team can develop their board one to two turns ahead of any fair response. Being monitored alongside Simian Spirit Guide for whether free-mana accelerants from hand collectively push the format's turn-one power ceiling too high." },

  { name: "Jeska's Will",              type: "Instant",                             cat: "combo",  discuss: "For each opponent, choose to add three red mana or exile the top card of that opponent's library and allow casting it this turn. In 2HC with two opponents, this produces six red mana, accesses two opposing library tops, or splits between both — all for two mana. The mana burst alone exceeds any fair ramp spell. In 2HC, the presence of two opponents makes the maximum ceiling of this card significantly higher than in any solo format, creating a high floor of at minimum six free mana mid-game." },

  { name: "Baral, Chief of Compliance", type: "Legendary Creature — Human Wizard",  cat: "combo",  discuss: "Being watched as a commander. Makes each instant and sorcery cost 1 less to cast. Whenever you counter a spell, draw a card then discard a card. In 2HC, Baral's cost reduction benefits the teammate's instants and sorceries as well — a passive discount across two players' spell packages is significantly stronger than in solo Commander. Combined with the card-filtering from counters and a teammate running interaction, Baral creates a mana and card advantage advantage that compounds every turn cycle." },

];
