/* ════════════════════════════════════════════════════════════════
   blog.js — rendering logic for Reflections.
   DO NOT edit this file to manage content — use blog-posts.js.
   ════════════════════════════════════════════════════════════════ */

(function () {
  'use strict';

  /* ── Helpers ────────────────────────────────────────────────── */

  function formatDate(iso) {
    var d = new Date(iso + 'T00:00:00');
    return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  }

  function escapeHtml(str) {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  /* ── Content block renderer ─────────────────────────────────── */

  function renderBlock(block) {
    switch (block.type) {
      case 'p':
        return '<p class="blog-p">' + escapeHtml(block.text) + '</p>';

      case 'h2':
        return '<h2 class="blog-h2">' + escapeHtml(block.text) + '</h2>';

      case 'h3':
        return '<h3 class="blog-h3">' + escapeHtml(block.text) + '</h3>';

      case 'blockquote':
        return '<blockquote class="blog-quote">' + escapeHtml(block.text) + '</blockquote>';

      case 'img':
        var cap = block.caption
          ? '<figcaption class="blog-fig-caption">' + escapeHtml(block.caption) + '</figcaption>'
          : '';
        return '<figure class="blog-figure">' +
          '<img src="' + escapeHtml(block.src) + '" alt="' + escapeHtml(block.alt || '') + '" class="blog-img">' +
          cap +
          '</figure>';

      default:
        return '';
    }
  }

  /* ── Card HTML builder ──────────────────────────────────────── */

  function buildCard(post) {
    var cover = post.coverImage
      ? '<div class="blog-card-cover"><img src="' + escapeHtml(post.coverImage) + '" alt="' + escapeHtml(post.coverAlt || '') + '"></div>'
      : '<div class="blog-card-cover blog-card-cover-empty"></div>';

    return '<article class="blog-card" data-slug="' + escapeHtml(post.slug) + '">' +
      cover +
      '<div class="blog-card-body">' +
        '<time class="blog-card-date">' + formatDate(post.date) + '</time>' +
        '<h2 class="blog-card-title">' + escapeHtml(post.title) + '</h2>' +
        '<p class="blog-card-excerpt">' + escapeHtml(post.excerpt) + '</p>' +
        '<span class="blog-card-cta">Read reflection →</span>' +
      '</div>' +
    '</article>';
  }

  /* ── Post list (index view) ─────────────────────────────────── */

  function renderList() {
    document.getElementById('blog-root').innerHTML =
      '<div class="container">' +
        '<div class="sec-label">Open to Discussion</div>' +
        '<h1 class="sec-title">Reflections</h1>' +
        '<p class="blog-intro">Ideas, perspectives, and format thinking — presented as starting points, not conclusions.</p>' +
        '<div class="blog-search-row">' +
          '<input type="text" id="blog-search" class="blog-search-input" placeholder="Search reflections…" autocomplete="off">' +
        '</div>' +
        '<div class="blog-grid" id="blog-grid"></div>' +
        '<p class="blog-no-results" id="blog-no-results" style="display:none">No reflections match your search.</p>' +
      '</div>';

    renderGrid(BLOG_POSTS);

    document.getElementById('blog-search').addEventListener('input', function (e) {
      var q = e.target.value.trim().toLowerCase();
      if (!q) { renderGrid(BLOG_POSTS); return; }
      var filtered = BLOG_POSTS.filter(function (p) {
        return p.title.toLowerCase().indexOf(q) !== -1 ||
               p.excerpt.toLowerCase().indexOf(q) !== -1;
      });
      renderGrid(filtered);
    });
  }

  function renderGrid(posts) {
    var grid = document.getElementById('blog-grid');
    var none = document.getElementById('blog-no-results');

    if (!posts.length) {
      grid.innerHTML = '';
      none.style.display = 'block';
      return;
    }

    none.style.display = 'none';
    grid.innerHTML = posts.map(buildCard).join('');

    grid.querySelectorAll('.blog-card').forEach(function (card) {
      card.addEventListener('click', function () {
        navigateTo(card.dataset.slug);
      });
    });
  }

  /* ── Share button builder ───────────────────────────────────── */

  var SHARE_CONFIG = {
    fb: {
      label: 'Facebook',
      color: 'fb',
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/></svg>',
      href: function (url) {
        return 'https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(url);
      },
    },
    reddit: {
      label: 'Reddit',
      color: 'reddit',
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0zm5.01 4.744c.688 0 1.25.561 1.25 1.249a1.25 1.25 0 0 1-2.498.056l-2.597-.547-.8 3.747c1.824.07 3.48.632 4.674 1.488.308-.309.73-.491 1.207-.491.968 0 1.754.786 1.754 1.754 0 .716-.435 1.333-1.01 1.614a3.111 3.111 0 0 1 .042.52c0 2.694-3.13 4.87-7.004 4.87-3.874 0-7.004-2.176-7.004-4.87 0-.183.015-.366.043-.534A1.748 1.748 0 0 1 4.028 12c0-.968.786-1.754 1.754-1.754.463 0 .898.196 1.207.49 1.207-.883 2.878-1.43 4.744-1.487l.885-4.182a.342.342 0 0 1 .14-.197.35.35 0 0 1 .238-.042l2.906.617a1.214 1.214 0 0 1 1.108-.701zM9.25 12C8.561 12 8 12.562 8 13.25c0 .687.561 1.248 1.25 1.248.687 0 1.248-.561 1.248-1.249 0-.688-.561-1.249-1.249-1.249zm5.5 0c-.687 0-1.248.561-1.248 1.25 0 .687.561 1.248 1.249 1.248.688 0 1.249-.561 1.249-1.249 0-.687-.562-1.249-1.25-1.249zm-5.466 3.99a.327.327 0 0 0-.231.094.33.33 0 0 0 0 .463c.842.842 2.484.913 2.961.913.477 0 2.105-.056 2.961-.913a.361.361 0 0 0 .029-.463.33.33 0 0 0-.464 0c-.547.533-1.684.73-2.512.73-.828 0-1.979-.196-2.512-.73a.326.326 0 0 0-.232-.095z"/></svg>',
      href: function (url, title) {
        return 'https://www.reddit.com/submit?url=' + encodeURIComponent(url) + '&title=' + encodeURIComponent(title);
      },
    },
    twitter: {
      label: 'X / Twitter',
      color: 'twitter',
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.748l7.73-8.835L1.254 2.25H8.08l4.253 5.622L18.244 2.25zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>',
      href: function (url, title) {
        return 'https://twitter.com/intent/tweet?url=' + encodeURIComponent(url) + '&text=' + encodeURIComponent(title);
      },
    },
    whatsapp: {
      label: 'WhatsApp',
      color: 'whatsapp',
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51a12.8 12.8 0 0 0-.57-.01c-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 0 1-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 0 1-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 0 1 2.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0 0 12.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 0 0 5.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 0 0-3.48-8.413z"/></svg>',
      href: function (url, title) {
        return 'https://api.whatsapp.com/send?text=' + encodeURIComponent(title + ' — ' + url);
      },
    },
  };

  function buildShareBtn(platform, slug, title) {
    var cfg = SHARE_CONFIG[platform];
    var url  = 'https://twoheadedcommander.com/blog.html#' + slug;
    return '<a class="blog-share-btn blog-share-' + cfg.color + '" ' +
      'href="' + cfg.href(url, title) + '" ' +
      'target="_blank" rel="noopener" aria-label="Share on ' + cfg.label + '">' +
      cfg.icon + cfg.label +
    '</a>';
  }

  /* ── Single post view ───────────────────────────────────────── */

  function renderPost(slug) {
    var post = null;
    for (var i = 0; i < BLOG_POSTS.length; i++) {
      if (BLOG_POSTS[i].slug === slug) { post = BLOG_POSTS[i]; break; }
    }

    if (!post) { renderList(); return; }

    var cover = post.coverImage
      ? '<div class="blog-post-cover"><img src="' + escapeHtml(post.coverImage) + '" alt="' + escapeHtml(post.coverAlt || '') + '"></div>'
      : '';

    var blocks = post.content.map(renderBlock).join('');

    document.getElementById('blog-root').innerHTML =
      '<div class="container blog-post-wrap">' +
        '<a href="#" class="blog-back" id="blog-back">← All reflections</a>' +
        cover +
        '<div class="blog-post-header">' +
          '<time class="blog-post-date">' + formatDate(post.date) + '</time>' +
          '<h1 class="blog-post-title">' + escapeHtml(post.title) + '</h1>' +
          '<p class="blog-post-disclaimer">This reflects one perspective on the format — we welcome discussion and disagreement.</p>' +
        '</div>' +
        '<div class="blog-post-body">' + blocks + '</div>' +
        '<div class="blog-share">' +
          '<span class="blog-share-label">Share this reflection</span>' +
          '<div class="blog-share-buttons">' +
            buildShareBtn('fb',       post.slug, post.title) +
            buildShareBtn('reddit',   post.slug, post.title) +
            buildShareBtn('twitter',  post.slug, post.title) +
            buildShareBtn('whatsapp', post.slug, post.title) +
          '</div>' +
          '<p class="blog-share-note">Note — social platforms show a preview of the Reflections page, not this specific post. The link still lands here.</p>' +
        '</div>' +
      '</div>';

    document.getElementById('blog-back').addEventListener('click', function (e) {
      e.preventDefault();
      navigateTo(null);
    });

    window.scrollTo(0, 0);
  }

  /* ── Hash-based routing ─────────────────────────────────────── */

  function getSlug() {
    var hash = location.hash.replace('#', '').trim();
    return hash || null;
  }

  function navigateTo(slug) {
    if (slug) {
      history.pushState({ slug: slug }, '', '#' + slug);
      renderPost(slug);
    } else {
      history.pushState({ slug: null }, '', location.pathname);
      renderList();
    }
  }

  window.addEventListener('popstate', function (e) {
    var slug = e.state && e.state.slug ? e.state.slug : getSlug();
    slug ? renderPost(slug) : renderList();
  });

  /* ── Init ───────────────────────────────────────────────────── */

  document.addEventListener('DOMContentLoaded', function () {
    var slug = getSlug();
    slug ? renderPost(slug) : renderList();
  });

}());
